### ISSUE TITLE
FreeBSD stores bash in /usr/local/bin/bash

### ISSUE THREAD

**Issue by steiny2k** [CarlosCuezva/dashboards-Grafana-Teslamate#10]
Hi,

thanks for this fine project. One minor remark since I run TeslaMate ein a FreeBSD jail, I stumbled over the shebang you're using in the bash script looking for bash in /bin/bash, where freebsd uses /usr/local/bin/bash.

You could make the script more platform agnostic by putting the shebang `#!/usr/bin/env bash`. See https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my for some info on the approach.

Best,
Seb

**Comment by CarlosCuezva** [comment]
Hi Seb!

Thanks for your comment, as soon as I have some free time I'll apply the change.

All the best

**Comment by CarlosCuezva** [comment]
Hi again!

I hope the problem has been fixed with the last [commit](https://github.com/CarlosCuezva/dashboards-Grafana-Teslamate/commit/2331b46c970183fc2e7fd87edc4c541255c73d89).

Please, if this change solves it, close the incident

Thanks again

Regards!
