### ISSUE TITLE
Add support for docker compose import

### ISSUE THREAD

**Issue by Deishelon** [CarlosCuezva/dashboards-Grafana-Teslamate#12]
As a user of both custom dashboards (this & https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards) 

Having an option to import dashboards from this repository via docker file, i.e:
```yml
volumes:
      - ~/Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml <---- this
      - ~/Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards <---- this
```
will be very handy, add config once, and git fetch/pull & recreate container when new update to dashboards are released. 

Reference implementation; https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards

Thanks!

**Comment by CarlosCuezva** [comment]
Hi @Deishelon!

Thanks for your suggestion, I've been looking at the process to add it to docker but it's much slower and more tedious than doing it through the **new dashboards.sh**.

With the new **dashboards.sh** with a single command, it downloads the latest release and installs (or updates) it automatically. Also, you can add it to crontab to always be up to date.

Regards
