### ISSUE TITLE
Syntax error in dashboards.sh

### ISSUE THREAD

**Issue by jorgecasar** [CarlosCuezva/dashboards-Grafana-Teslamate#14]
After running `sh dashboards.sh` it throws the following error:

```
dashboards.sh: 36: Syntax error: "(" unexpected (expecting "}")
```

**Comment by CarlosCuezva** [comment]
Can you tell me all the steps you have taken to try to repeat the error?

What OS are you using?

**Comment by jorgecasar** [comment]
I downloaded the repo in Ubuntu server. And tried to run the script as described above.

**Comment by CarlosCuezva** [comment]
Hey mate!

I found your problem. You are trying to execute it with:

`sh dashboards.sh`

But, you have to use:

`./dashboards.sh`

**Comment by federicotravaini** [comment]
> I downloaded the repo in Ubuntu server. And tried to run the script as described above.

You downloaded the HTML page and not the script. This is why you get that error.

**Comment by jorgecasar** [comment]
@CarlosCuezva thanks! that works!

@federicotravaini I cloned the repository, the file content is correct

**Comment by CarlosCuezva** [comment]
@jorgecasar if it's solved, can I close the issue?
