### ISSUE TITLE
Unable to View Charge Cost

### ISSUE THREAD

**Issue by droideggs** [CarlosCuezva/dashboards-Grafana-Teslamate#18]
How do I view charge cost graph? When I select the graph the cost amount is empty.

**Comment by CarlosCuezva** [comment]
Can you give me more information, please? dashboard name, screenshot,...

**Comment by droideggs** [comment]
i realized my issue is from a different github (jheredianet) dev, my apologies. seems like you guys both have the same exact custom dashboards. the dashboard is in reference to charging cost stats. in general do i need to install something separate to view charge costs for various superchargers i went to?

**Comment by CarlosCuezva** [comment]
Ahhh ok, don't worry and I'm sorry but I can't help you with his dashboard, I didn't test it
