### ISSUE TITLE
natel-plotly-panel & other custom Plugins have been removed

### ISSUE THREAD

**Issue by swiffer** [CarlosCuezva/dashboards-Grafana-Teslamate#27]
natel-plotly-panel & other custom Plugins have been removed in the latest Teslamate grafana version (replaced via xy chart & geomap - natively available in latest grafana releases).

https://github.com/teslamate-org/teslamate/commit/1796294442566a8f504f0eda052603ef4228a9f7

Would be great to See custom Dashboards updated so they continue working Just fine!

**Comment by CarlosCuezva** [comment]
Thanks for the notice, I'll check it out as soon as possible.

**Comment by CarlosCuezva** [comment]
Hi again

I just updated the dashboards so that they are fully compatible with the new version of Teslamate.

Thanks again for letting me know

**Comment by swiffer** [comment]
Thanks reacting so fast!
