### ISSUE TITLE
charging-curves.json is pulled/restored but not placed or updated in the directory

### ISSUE THREAD

**Issue by denzel1994** [CarlosCuezva/dashboards-Grafana-Teslamate#28]
Hey,

with the newest release v1.23.3 and Teammate 1.28.2 the charging-curves.json was not autoupdated correctly. So I deleted it from the dashboards folder and ran the dashboards.sh again manually.

With the script saying it was pulled and restored. (12 dashboards restored)
<img width="409" alt="Bildschirmfoto 2023-11-27 um 23 27 00" src="https://github.com/CarlosCuezva/dashboards-Grafana-Teslamate/assets/36551243/26a13572-4390-4b34-b7a4-2447ff6442f1">

However it is nowhere to be found. (only 11 dashboards)
<img width="1381" alt="Bildschirmfoto 2023-11-27 um 23 26 16" src="https://github.com/CarlosCuezva/dashboards-Grafana-Teslamate/assets/36551243/72861de2-fccf-4d06-bf68-a8627fba4c99">

I had to manually import it.
Any idea?

**Comment by CarlosCuezva** [comment]
Thanks for the notice, I'll check it out as soon as possible.

**Comment by CarlosCuezva** [comment]
Hi again

I just check de autoinstaller and it works correctly.

I made some changes to the "Charging Curves" dashboard, then I saved it, tried the autoinstaller and it updated me to the latest version published on GitHub.

**Comment by denzel1994** [comment]
Thanks for checking so quickly. :)

That's weird. Then there must be something with my installation. All other dashboards update correctly or get restored when deleted manually.

<img width="653" alt="Bildschirmfoto 2023-11-28 um 22 04 42" src="https://github.com/CarlosCuezva/dashboards-Grafana-Teslamate/assets/36551243/ceb5b321-e11c-4971-bbe7-bfdd1edc1e63">

**Comment by CarlosCuezva** [comment]
If it is strange, I have tried updating it, deleting it and installing it from 0 and it always works for me.

It can be queried through the Grafana API, but it doesn't tell you if there is a problem.
