### ISSUE TITLE
costes en SuC / other DC

### ISSUE THREAD

**Issue by rover0** [CarlosCuezva/dashboards-Grafana-Teslamate#3]
Hola,
He cargado muy raramente en DC no SuC Tesla, y en los paneles correspondientes sale casi todo el coste (como 2/3) para "Otros DC". Me da la impresión de que algo falla con eso para distinguir unos de otros ¿cómo se hace?
Saludos,
Roberto

**Comment by CarlosCuezva** [comment]
Hola

¿A qué panel te refieres? De todas formas, para distinguir si es en un SuC o no, es si la dirección de la carga o la geovalla contiene la palabra SuperCharger o no.

**Comment by rover0** [comment]
El geofence correspondiente al cargador debe contener "Supercharger" en la dirección (pero hay unos cuantos que no lo cumplen: Fuentespina y Nuevos Ministerios al menos), o en el geofence, donde yo uso "SuC" en vez de Supercharger. Yo he añadido OR geo.name LIKE '%SuC%' y eso me soluciona el coste de los Supercharger, pero el "other DC" sigue con cifras infladas (me he metido en la base de datos y he cargado en no-Tesla dos veces en total desde que tengo Teslamate). El problema ahí es que la query debe ser AND en vez de OR: (addr.name NOT LIKE '%Supercharger%' **AND** geo.name NOT LIKE '%Supercharger%' AND geo.name '%SuC%').

**Comment by rover0** [comment]
me refiero al panel "Charging Costs Stats"

**Comment by CarlosCuezva** [comment]
Aquí hay 2 problemas principalmente. 

El primero es el sistema de geolocalización propia que usa Teslamate y que no siempre te coge la dirección deseada, pero cuando la nombra bien, siempre lleva incluida la palabra Supercharger, aquí te dejo una captura de pantalla con varios SuCs y otros DCs.
![image](https://user-images.githubusercontent.com/5815421/210354473-ea7cca7b-7623-45f1-a93b-ab6b1cbef8c4.png)

El segundo problema es que no se puede hacer una adaptación para cada persona, entonces si se crea una geovalla lo "ideal" es que se llamen tal y como vienen las direcciones, porque también se podría escribir S.u.C. o suc y con distincción de mayúsculas y minísculas...

En cuanto al primer punto si ves alguna que está mal, por ahora la única forma de arreglarlo es editando directamente la base de datos.

Te dejo aquí el enlace para que veas como sería el JSON que devuelve la petición para obtener las direcciones, ese justo es el de Aranda (me ha costado que lo pille bien y ahí es donde a veces Teslamate tiene problemas en asignar correctamente la dirección)

https://nominatim.openstreetmap.org/reverse?format=json&lat=41.6233233&lon=-3.6878468&zoom=27&addressdetails=1

**Comment by rover0** [comment]
Lo de los nombres lo entiendo, es discutible cómo llama la gente a los SuC y si se dice en el manual es fácil cambiar los nombres y que salga bien

Pero la query para los DC no-SuC está mal, tiene que ser

addr.name NOT LIKE '%Supercharger%' **AND** geo.name NOT LIKE '%Supercharger%', si es NOT LIKE **OR** NOT LIKE, si ocurre que a alguien se le escapa un nombre sin Supercharger, o a tesla se les escapa como en Nuevos Ministerios que tampoco lo pone (o no lo ponía cuando entró en mi base de datos), entonces esa carga se va a suma a los DC no-SuC. Es bastante más difícil que fallen las dos cosas, sobre todo cuando  una de ellas la controla el usuario como es el nombre, y entiendo que para eso se usan las dos cosas, addr.name y geo.name, si ambas tienen que tener la palabra Supercharger ¿para qué usar los dos?

**Comment by rover0** [comment]
Como muestra: nombres corregidos, con la query con OR la suma no coincide y claramente está inflado el importe DC-no-SuC:
<img width="1033" alt="Screenshot 2023-01-03 at 16 51 46" src="https://user-images.githubusercontent.com/7938210/210393004-6d70b735-219e-41b2-b5ea-bc88606d6344.png">

Con la query corregida con AND la suma cuadra:
<img width="1033" alt="Screenshot 2023-01-03 at 16 52 19" src="https://user-images.githubusercontent.com/7938210/210392970-60e6c3f3-7749-4674-bc55-038787e70992.png">

**Comment by CarlosCuezva** [comment]
Estoy revisándolo porque tal y como lo planteas con el AND, sino una carga no tiene asociada una geovalla no lo computa.

Puedes probar a cambiar el SELECT de dentro del WITH y poner este:

`SELECT DISTINCT c.charging_process_id`

Y dejando el OR de: `AND (addr.name NOT LIKE '%Supercharger%' OR geo.name NOT LIKE '%Supercharger%')`

**Comment by CarlosCuezva** [comment]
Bueno he conseguido por fin reproducir el problema, voy a revisar las queries

**Comment by CarlosCuezva** [comment]
He subido un cambio en ambos dashboards y si el fallo es el que he encontrado, ya te debería funcionar correctamente.

**Comment by rover0** [comment]
Efectivamente parece arreglado, muchas gracias, me encantan!
