### ISSUE TITLE
Energy added in Current Charge View not correctly displayed

### ISSUE THREAD

**Issue by Starmixcraft** [CarlosCuezva/dashboards-Grafana-Teslamate#9]
The Energy added Select in the Current Charge View dose not display correctly.
![image](https://user-images.githubusercontent.com/36541632/215453875-f33727de-685b-46a0-a231-75e3bb8ffbd0.png)
![image](https://user-images.githubusercontent.com/36541632/215453939-95c61880-4d0e-4268-a36c-0a63e7849fbd.png)
![image](https://user-images.githubusercontent.com/36541632/215454368-22dfdf3b-71ea-4793-80f3-467f8679841c.png)
I have tracked this down to this line in the SQL:
`SELECT NOW() as time, MAX(c.charge_energy_added) - MIN(c.charge_energy_added) as charge_energy_added`
by removing `- MIN(c.charge_energy_added)` it displays correctly for me.
![image](https://user-images.githubusercontent.com/36541632/215454446-ee79c66f-0bf9-4241-bf47-7fc3afeee909.png)

**Comment by CarlosCuezva** [comment]
Thanks for the notice, I'll check it out.

**Comment by CarlosCuezva** [comment]
Hi again!

I hope that the problem was fixed in release [v1.13.1](https://github.com/CarlosCuezva/dashboards-Grafana-Teslamate/releases/tag/v1.13.1).

Actually the problem was not the MIN but when more than 1 recharge is registered in Teslamate in the selected period of time.

![image](https://user-images.githubusercontent.com/5815421/215552121-745e4ce3-1cb5-48fb-a183-4f34e59153b0.png)

![image](https://user-images.githubusercontent.com/5815421/215552497-29551d12-270e-44d4-836d-3869031ce857.png)

Can you do me a favor to check if it is solved with the new version?

Thanks again

**Comment by Starmixcraft** [comment]
Hi,
thanks for the quick fix.
I will install the new version right away.

Actually, I think the problem is something else, I have checked my charges dashboard and there was only one charge registered. I also only have one tesla registered in Teslamate, therefor interference by another car's data is also ruled out.

Il get back to you as once I can confirm or deny a fix (May take a few days).

Off-topic: Your dashboard extension is really amazing, I love it :D

**Comment by CarlosCuezva** [comment]
Hi!

When you have been able to try it, tell me if it worked for you or not.

I'm glad you love them ;)

**Comment by Starmixcraft** [comment]
Hi,
sadly, the fix did not work as intended.
I tried finding the culprit and think it's the time filter.
The bug only accrues if the charging session is longer than 1h, because the default time filter is set to 1h.

Example:
Data point 1 at 09:00:00 charged 0kwh.
Data point 2 at 09:30:00 charged 6kwh.
Data point 3 at 10:00:00 charged 11kwh.

If we now trigger the request at 10:00:01 with the filter set to 1h, it will only return data point 2 and 3, therefor min() returns 6kwh and max() 11kwh. Increasing the default time filter does fix the bug, but this is not a nice fix, theoretical a charge could take a very long time if you charge by wall plug with minimum current. Maybe quarrying the last charge for the start time and setting that as the min time could solve the problem.

**Comment by CarlosCuezva** [comment]
Ok now I understand, so I solved a part because I interpret it as how much energy you have recharged in that period of time.

Well, I have come up with an option to show your approach and mine at the same time. I'll see if I can do it.

**Comment by CarlosCuezva** [comment]
I think that with this change the data for the selected period and the current recharge session would be displayed correctly

![](https://user-images.githubusercontent.com/5815421/216051220-f9c72043-25cb-45a2-b9bd-8de2a5aa7ce9.png)

**Comment by CarlosCuezva** [comment]
I have uploaded new changes ;)

**Comment by Starmixcraft** [comment]
Thanks for the fix,
I have already installed the new version and it works great.
Hopefully this will prevent any further confusion between the 2 values.
From my side the issue can be closed, unless you noticed any other problems.

**Comment by CarlosCuezva** [comment]
Thank you!

It is true that before each person could interpret it differently.

Ok, I close it ;)

Regards
